# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

er_diameterCpp <- function(n, m) {
    .Call('_rweboflife_er_diameterCpp', PACKAGE = 'rweboflife', n, m)
}

giant_componentCpp <- function(n, m) {
    .Call('_rweboflife_giant_componentCpp', PACKAGE = 'rweboflife', n, m)
}

nestednessCpp <- function(M) {
    .Call('_rweboflife_nestednessCpp', PACKAGE = 'rweboflife', M)
}

