# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

nestednessCpp <- function(M) {
    .Call('_rweboflife_nestednessCpp', PACKAGE = 'rweboflife', M)
}

null_swapCpp <- function(M, iter_max) {
    .Call('_rweboflife_null_swapCpp', PACKAGE = 'rweboflife', M, iter_max)
}

inversePercolationCpp <- function(EL) {
    .Call('_rweboflife_inversePercolationCpp', PACKAGE = 'rweboflife', EL)
}

