# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

er_diameterCpp <- function(n, m) {
    .Call('_rweboflife_er_diameterCpp', PACKAGE = 'rweboflife', n, m)
}

giant_componentCpp <- function(edges_c_arr, len_c_arr) {
    .Call('_rweboflife_giant_componentCpp', PACKAGE = 'rweboflife', edges_c_arr, len_c_arr)
}

nestednessCpp <- function(M) {
    .Call('_rweboflife_nestednessCpp', PACKAGE = 'rweboflife', M)
}

null_swapCpp <- function(M, iter) {
    .Call('_rweboflife_null_swapCpp', PACKAGE = 'rweboflife', M, iter)
}

inversePercolationCpp <- function(EL) {
    .Call('_rweboflife_inversePercolationCpp', PACKAGE = 'rweboflife', EL)
}

