#@author alessandro vindigni, https://github.com/vindignia/


name: Check R-weboflife on macOS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  R-CMD-check:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2'

      - name: Install system dependencies (macOS)
        run: |
          brew install libxml2 curl openssl
          export LDFLAGS="-L/usr/local/opt/libxml2/lib -L/usr/local/opt/openssl/lib"
          export CPPFLAGS="-I/usr/local/opt/libxml2/include -I/usr/local/opt/openssl/include"

      - name: Install R package dependencies
        run: |
          R -e 'install.packages("Rcpp")'
          R -e 'install.packages("RcppArmadillo")'
          R -e 'install.packages(c("remotes", "testthat"))'
          R -e 'remotes::install_deps(dependencies = TRUE)'

      - name: Find Rcpp.h to update the path in the file ./src/Makevars
        run: sudo find / -name Rcpp.h

      - name: Find RcppArmadillo.h to update the path in the file ./src/Makevars
        run: sudo find / -name RcppArmadillo.h

      - name: Install package
        run: R CMD INSTALL .

      - name: Run unit tests with testthat
        run: Rscript -e 'testthat::test_dir("tests")'

      - name: Session info
        run: Rscript -e 'sessionInfo()'

