name: R-CMD-check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/setup-node@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libxml2-dev libcurl4-openssl-dev libssl-dev

      - name: Install R package dependencies
        run: |
          install.packages('devtools')
          install.packages('remotes')
          devtools::install_deps(dependencies = TRUE)

      - name: Install package
        run: R CMD INSTALL .

      - name: Run tests
        run: Rscript -e 'devtools::test()'

      - name: Session info
        run: Rscript -e 'sessionInfo()'

