#@author alessandro vindigni, https://github.com/vindignia/

name: Check R-weboflife

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      # Add this step to print runner environment details
      - name: List contents of R include directory
        run: ls /opt/R/4.4.1/lib/R/include

      - name: Install Rcpp
        run: R -e 'install.packages("Rcpp")'

      # Add a step to run find command
      - name: Find Rcpp.h
        run: sudo find /  -name Rcpp.h

      # - name: Install system dependencies
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y libxml2-dev libcurl4-openssl-dev libssl-dev
      #
      # - name: Install R package dependencies
      #   run: |
      #     R -e 'install.packages(c("remotes", "testthat"))'
      #     R -e 'remotes::install_deps(dependencies = TRUE)'
      #
      # - name: Install package
      #   run: R CMD INSTALL .
      #
      # - name: Run tests
      #   run: Rscript -e 'devtools::test()'
      #
      # - name: Session info
      #   run: Rscript -e 'sessionInfo()'

